os: linux
language: c

branches:
  only:
    - main

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  cleanup: false
  local_dir: docs/html
  token: $GH_REPO_TOKEN
  on:
    branch: main
