os: linux
language: c

branches:
  only:
    - main

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages:git
  keep_history: false
  cleanup: false
  local_dir: docs/html
  token: $GH_REPO_TOKEN
  edge: true
  on:
    branch: main
