name: Documentation

on:
  push:
    branches:
      -main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
        uses: actions/checkout@v2

      - name: generate_doxygen
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: deploy_doxygen
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
